export enum ErrorCode {
COUNTRY_NOT_FOUND = 'COUNTRY_NOT_FOUND',
NOT_FOUND = 'NOT_FOUND',
NETWORK_ERROR = 'NETWORK_ERROR',
SERVER_ERROR = 'SERVER_ERROR',
UNAUTHORIZED = 'UNAUTHORIZED',
VALIDATION_ERROR = 'VALIDATION_ERROR',
UNKNOWN = 'UNKNOWN'
}